name: iotpower-parser-linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: prepare software
      run: |
        sudo apt update
        sudo apt install libudev-dev
        rustup update
    - name: clone repo
      env:
        GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
      run: |
        cd ..
        git clone --branch=master https://${GITHUBTOKEN}:x-oauth-basic@github.com/chenxuuu/IOT-Power-Client
    - name: build
      run: |
        mkdir iotpower-parser-linux-x64/
        cd ../IOT-Power-Client/iot_parser
        cargo build --release
        cd -
        cp ../IOT-Power-Client/iot_parser/target/release/*.so iotpower-parser-linux-x64/
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: iotpower-parser-linux-x64
        path: iotpower-parser-linux-x64/
