name: luatools
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      shell: pwsh
      env:
        LUATOOLS2REPO: ${{ secrets.LUATOOLS2REPO }}
      run: |
        .\retry_clone_luatools.ps1
        cd luatools_py3
        python -V
        pip install -r requirement.txt
    - name: prepare python
      run: |
        cd c:/
        Invoke-WebRequest https://github.com/openLuat/LuatOS/releases/download/v0.0.1/Python37-32.7z -OutFile Python37-32.7z
        7z x Python37-32.7z
    - name: build
      run: |
        cd luatools_py3
        ./build_luat_x86.bat
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: luatools
        path: luatools_py3/Luatools_v2_x86.exe
