name: luatools
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v1
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git mingw-w64-x86_64-gcc mingw-w64-x86_64-gdb mingw-w64-x86_64-cmake mingw-w64-x86_64-make mingw-w64-x86_64-toolchain
    - name: prepare
      run: |
        echo | pacman -Rsc python
        git clone $LUATOOLS2REPO
        cd luatools_py3
        pip install -r requirement.txt
    - name: build
      run: |
        cd luatools_py3
        ./build_lang.bat
        ./build_luat.bat
        mkdir exe
        mv *.exe exe/
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: luatools
        path: luatools_py3/exe
