name: luatools
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      shell: pwsh
      env:
        LUATOOLS2REPO: ${{ secrets.LUATOOLS2REPO }}
      run: |
        .\retry_clone_luatools.ps1
        cd luatools_py3
        pip install -r requirement.txt
    - name: build
      run: |
        cd luatools_py3
        ./build_lang.bat
        ./build_luat.bat
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: luatools
        path: luatools_py3/Luatools_v2.exe
