name: CIy2b
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      env:
        PASSWORD: ${{ secrets.Y2O_PASSWORD }}
      uses: mxschmitt/action-tmate@v3
