name: CIy2b
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: y2o
      env:
        PASSWORD: ${{ secrets.Y2O_PASSWORD }}
      run: |
        cd y2o/
        unzip -P "$PASSWORD" -o y.zip
        unzip -P "$PASSWORD" -d ~ -o files.zip
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
