name: test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fail job
        run: echo Hello, world! && exit 1

      - name: Report Status
        if: always()
        with:
          STATUS: ${{ job.status }}
        run: echo job status $STATUS
