name: test
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: fail job
      run: |
        echo Hello, world!

    - name: report if failure
      if: always()
      env:
        STATUS: ${{ job.status }}
      run: |
        if [ "$STATUS" = "failure" ];then echo xxxxxxxxxxxxxx; fi
