name: y2o

on:
  push:
    paths:
      - 'y2o/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: y2o
        env:
          PASSWORD: ${{ secrets.Y2O_PASSWORD }}
        run: |
          sudo apt install -y ffmpeg
          sudo pip3 install youtube-dl
          curl https://rclone.org/install.sh | sudo bash
          cd y2o/
          unzip -P "$Y2O_PASSWORD" -d ~ -o files.zip
          unzip -P "$Y2O_PASSWORD" -o y.zip
          cd y/
          cat ../url.txt | while read line; do echo start download "$line";youtube-dl "$line" --cookies cookies.txt; done
          for filename in `find . -type f \( -name "*.mp4" -o -name "*.mkv" \)`; do echo start upload $filename; rclone move $filename remote:/others/for_share/video/yua done
